name: cmd-chall
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - _pytorch_select=0.1=cpu_0
  - blas=1.0=mkl
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2021.7.5=h06a4308_1
  - certifi=2021.5.30=py37h06a4308_0
  - cffi=1.14.6=py37h400218f_0
  - cudatoolkit=11.1.74=h6bb024c_0
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.10.4=h5ab3b9f_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - intel-openmp=2019.4=243
  - jpeg=9b=h024ee3a_2
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libiconv=1.15=h63c8f33_5
  - libidn2=2.3.2=h7f8727e_0
  - libmklml=2019.0.5=0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuv=1.40.0=h7b6447c_0
  - libwebp-base=1.2.0=h27cfd23_0
  - lz4-c=1.9.3=h2531618_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py37he8ac12f_0
  - mkl_fft=1.3.0=py37h54f3939_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - ncurses=6.2=he6710b0_1
  - nettle=3.7.3=hbbd107a_1
  - ninja=1.10.2=hff7bd54_1
  - numpy=1.19.2=py37h54aff64_0
  - numpy-base=1.19.2=py37hfa32c7d_0
  - olefile=0.46=py37_0
  - openh264=2.1.0=hd408876_0
  - openjpeg=2.3.0=h05c96fa_1
  - openssl=1.1.1k=h27cfd23_0
  - pillow=8.3.1=py37h2c7a002_0
  - pip=21.1.3=py37h06a4308_0
  - pycparser=2.20=py_2
  - python=3.7.10=h12debd9_4
  - pytorch=1.9.0=py3.7_cuda11.1_cudnn8.0.5_0
  - readline=8.1=h27cfd23_0
  - setuptools=52.0.0=py37h06a4308_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=hc218d9a_0
  - tk=8.6.10=hbc83047_0
  - torchaudio=0.9.0=py37
  - torchvision=0.10.0=py37_cu111
  - typing-extensions=3.10.0.0=hd3eb1b0_0
  - typing_extensions=3.10.0.0=pyh06a4308_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - backcall==0.2.0
    - charset-normalizer==2.0.3
    - click==8.0.1
    - colorama==0.4.4
    - decorator==5.0.9
    - dominate==2.6.0
    - filelock==3.0.12
    - gitdb==4.0.7
    - gitpython==3.1.18
    - huggingface-hub==0.0.12
    - humanize==3.10.0
    - idna==3.2
    - importlib-metadata==4.6.1
    - ipdb==0.13.9
    - ipython==7.25.0
    - ipython-genutils==0.2.0
    - jedi==0.18.0
    - joblib==1.0.1
    - jsonpickle==1.5.2
    - matplotlib-inline==0.1.2
    - msgpack==1.0.2
    - munch==2.5.0
    - packaging==21.0
    - pandas==1.3.1
    - parso==0.8.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - prompt-toolkit==3.0.19
    - psutil==5.8.0
    - ptyprocess==0.7.0
    - py-cpuinfo==8.0.0
    - pygments==2.9.0
    - pyparsing==2.4.7
    - python-dateutil==2.8.2
    - pytz==2021.1
    - pyyaml==5.4.1
    - regex==2021.7.6
    - requests==2.26.0
    - sacred==0.8.2
    - sacremoses==0.0.45
    - scikit-learn==0.24.2
    - scipy==1.7.0
    - smmap==4.0.0
    - threadpoolctl==2.2.0
    - tokenizers==0.10.3
    - toml==0.10.2
    - tqdm==4.61.2
    - traitlets==5.0.5
    - transformers==4.9.1
    - urllib3==1.26.6
    - wcwidth==0.2.5
    - wrapt==1.12.1
    - zipp==3.5.0
prefix: /users/maxbain/miniconda3/envs/cmd-chall
